---
namespace: redhatinsights
name: insights
version: 0.0.1-devel
readme: README.md
authors:
- Will Tome (@wtome)
description: Ansible Collection for Red Hat insights
repository: https://github.com/redhatinsights/ansible-collections-insights
build_ignore:
- release.yml
- .gitignore
- changelogs/.plugin-cache.yaml
- tests/output
license:
- Apache-2.0
