---
- name: Release collection
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    collection_namespace: "{{ namespace  | lower }}"
    collection_name: insights
    collection_version: "{{ github_tag.split('/')[-1] | regex_search('(\\d.\\d.\\d.*)') }}"
    collection_repo: https://github.com/redhatinsights/ansible-collections-insights
    api_key: undef

  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        collection_archive: "{{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz"

    - name: Update namespace and name
      block:
        - name: Fix namespace and name references in files
          ansible.builtin.replace:
            path: "{{ playbook_dir }}/{{ item }}"
            regexp: redhat.insights
            replace: "{{ collection_namespace }}.{{ collection_name }}"
          loop:
            - docs/inventory.md
            - plugins/inventory/insights.py
            - roles/compliance/tests/compliance.yml
            - roles/compliance/tests/install-only.yml
            - roles/compliance/tests/run-only.yml
            - roles/insights_client/tests/example-insights-client-playbook.yml
            - tests/inventory/insights.yml

    - name: Create galaxy.yml
      ansible.builtin.template:
        src: "{{ playbook_dir }}/galaxy.yml.j2"
        dest: "{{ playbook_dir }}/galaxy.yml"
        mode: "u=rw,go=r"

    - name: Build collection
      ansible.builtin.command:
        argv:
          - ansible-galaxy
          - collection
          - build
        chdir: "{{ playbook_dir }}"
        creates: "{{ playbook_dir }}/{{ collection_archive }}"
      tags: build

    - name: Install collection
      ansible.builtin.command:
        argv:
          - ansible-galaxy
          - collection
          - install
          - "{{ collection_archive }}"
          - -p
          - ~/.ansible/collections/
        chdir: "{{ playbook_dir }}"
      changed_when: true
      tags: install

    - name: Publish collection
      ansible.builtin.command:
        argv:
          - ansible-galaxy
          - collection
          - publish
          - "--api-key={{ api_key }}"
          - "{{ collection_archive }}"
        chdir: "{{ playbook_dir }}"
      changed_when: true
      tags: publish

    - name: Git cleanup
      # noqa: command-instead-of-module the git module does not do 'clean'
      ansible.builtin.command:
        argv:
          - git
          - reset
          - --hard
      changed_when: true
      tags: cleanup

    - name: Remove galaxy.yml
      ansible.builtin.file:
        path: "{{ playbook_dir }}/galaxy.yml"
        state: absent
      tags: cleanup
