---
- name: Release collection
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    collection_namespace: "{{ namespace  | lower }}"
    collection_name: insights
    collection_version: "{{ github_tag.split('/')[-1] | regex_search('(\\d.\\d.\\d.*)') }}"
    collection_repo: https://github.com/redhatinsights/ansible-collections-insights
    api_key: undef

  tasks:
    - name: Update namespace and name
      block:
        - name: Fix inventory plugin
          ansible.builtin.replace:
            path: "{{ playbook_dir }}/plugins/inventory/insights.py"
            regexp: redhat.insights
            replace: "{{ collection_namespace }}.{{ collection_name }}"

        - name: Fix role test
          ansible.builtin.replace:
            path: "{{ playbook_dir }}/roles/insights_client/tests/example-insights-client-playbook.yml"
            regexp: redhat.insights
            replace: "{{ collection_namespace }}.{{ collection_name }}"

    - name: Create galaxy.yml
      ansible.builtin.template:
        src: "{{ playbook_dir }}/galaxy.yml.j2"
        dest: "{{ playbook_dir }}/galaxy.yml"
        mode: "u=rw,go=r"

    - name: Build collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection build
        chdir: "{{ playbook_dir }}"
        creates: "{{ playbook_dir }}/{{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz"
      tags: build

    - name: Install collection
      ansible.builtin.command:
        cmd: "ansible-galaxy collection install {{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz -p ~/.ansible/collections/"
        chdir: "{{ playbook_dir }}"
      changed_when: true
      tags: install

    - name: Publish collection
      ansible.builtin.command:
        cmd: "ansible-galaxy collection publish --api-key={{ api_key }} {{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz"
        chdir: "{{ playbook_dir }}"
      changed_when: true
      tags: publish

    - name: Git cleanup
      # noqa: command-instead-of-module the git module does not do 'clean'
      ansible.builtin.command:
        cmd: git reset --hard
      changed_when: true
      tags: cleanup

    - name: Remove galaxy.yml
      ansible.builtin.file:
        path: "{{ playbook_dir }}/galaxy.yml"
        state: absent
      tags: cleanup
