---
- name: Check for Insights configuration
  ansible.builtin.assert:
    that: ansible_local.insights is defined
    fail_msg: Unable to find insights fact. Have you installed the insights client?

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml

- name: Include run tasks
  ansible.builtin.include_tasks: run.yml
