---
name: ansible-lint
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  ansibe-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
